spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sharespace?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.naver.com
    port: 465
    username: teamsharespace@naver.com
    password: ${MAIL_SMTP_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.naver.com
      mail.debug: true

kakao:
  url: https://dapi.kakao.com/v2/local/search/address.json?query=
  api-key: ${KAKAO_API_KEY}

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    stack.auto: false
    s3:
      bucket: ${BUCKET_NAME}
    region:
      static: ${AWS_REGION}
    stack:
      auto: false

#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
