spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sharespace?useSSL=false&serverTimezone=UTC
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

kakao:
  url: https://dapi.kakao.com/v2/local/search/address.json?query=
  api-key: ${KAKAO_API_KEY}
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
