name: Java CI with Gradle

on:
  push:
    branches: [ "release" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Create application-release.yml from secret
        run: |
          cd ./src/main/resources
          touch ./application-release.yml
          echo "${{ secrets.APPLICATION }}" >> ./application-release.yml
        shell: bash

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: docker image build
        run: |
          docker build -f Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/sharespace .

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: docker Hub push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/sharespace:latest
